    var games = [

    {
      id: 110,
      name: "双轮成行",
      nameEn: "WheelMates",
      date: "2026-09-07",
      developer: "Firevolt",
      publisher: "Firevolt",
      genres: ["合作","竞速","解谜","冒险"],
      genreClass: "adventure",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "双人合作驾驶迷你RC小车的竞速冒险游戏。在神秘教授的迷宫实验室中穿行，通过摆绳装置、磁力车轮、磁力抓取等能力升级解决谜题，探索隐藏路径。支持在线合作、同屏/分屏合作、跨平台多人、远程同乐。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3905450/WheelMates/",
      topicAngles: ["双人合作RC小车冒险玩法","分屏合作游戏的社交体验","独立合作解谜游戏市场观察"]
    },
    {
      id: 60,
      name: "万圣节：游戏",
      nameEn: "Halloween: The Game",
      date: "2026-09-08",
      developer: "IllFonic / Gun Interactive",
      publisher: "IllFonic Publishing",
      genres: ["恐怖","非对称对抗","多人","生存"],
      genreClass: "horror",
      platforms: ["Steam","PS5","Xbox"],
      price: "¥137(标准版)",
      chinese: true,
      hot: true,
      desc: "基于约翰·卡朋特1978年经典恐怖电影改编的非对称多人恐怖游戏，玩家可扮演迈克尔·迈尔斯追猎平民或作为居民求生，虚幻引擎5打造。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/3219630/Halloween/",
      topicAngles: ["经典恐怖电影IP改编游戏深度体验","非对称恐怖品类进化：从黎明杀机到万圣节沙盒","发售恰逢万圣节季节恐怖游戏氛围营销话题"]
    },
    {
      id: 155,
      name: "兽人递增",
      nameEn: "Orc Incremental",
      date: "2026-09-08",
      developer: "Nice Ride",
      publisher: "Playsaurus",
      genres: ["增量","自动战斗","RPG","策略"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "$7.99(约¥57)",
      chinese: true,
      hot: false,
      desc: "增量式自动战斗RPG，逐步增强兽人军队实力，策略性分配资源与升级路线，体验轻松但深度的增量策略玩法。支持简体中文。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4047270/Orc_Incremental/",
      topicAngles: ["增量游戏品类的市场观察","自动战斗RPG的玩法深度"]
    },
    {
      id: 164,
      name: "巴士模拟器27",
      nameEn: "Bus Simulator 27",
      date: "2026-09-08",
      developer: "Simteract",
      publisher: "astragon Entertainment",
      genres: ["模拟驾驶","经营","开放世界","多人"],
      genreClass: "simulation",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "系列最新作，驾驶官方授权巴士经营运输公司。首次引入长途客运路线与官方授权客车，支持跨平台联机合作。预购可获得豪华包DLC。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2397320/Bus_Simulator_27/",
      topicAngles: ["巴士模拟系列首次引入长途客运","模拟驾驶游戏跨平台联机体验"]
    },
    {
      id: 165,
      name: "畸域零",
      nameEn: "SPRAWL zero",
      date: "2026-09-08",
      developer: "MAETH",
      publisher: "Kwalee",
      genres: ["FPS","赛博朋克","快节奏","射击"],
      genreClass: "shooter",
      platforms: ["Steam","Epic","PS5","Xbox","Switch 2"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "致敬2000年代FPS黄金时代的快节奏射击游戏。扮演半机械超级士兵FIVE，在军阀统治与邪教狂热的赛博朋克城市中求生。重力手套、强化义体与40+种武器助你碾碎一切敌人。支持简繁中文。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3748520/SPRAWL_zero/",
      topicAngles: ["2000年代FPS黄金时代的复古复兴","40+武器系统的Build构筑深度","赛博朋克FPS的视觉与玩法创新"]
    },
    {
      id: 202,
      name: "蜂巢：异星世界",
      nameEn: "Honeycomb: The World Beyond",
      date: "2026-09-08",
      developer: "Frozen Way Studio",
      publisher: "Snail Games USA",
      genres: ["生存沙盒","开放世界","生物工程","建造","科幻"],
      genreClass: "adventure",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "科幻生存沙盒游戏，在外星球Sota7上进行生物工程探索。杂交动植物、收集资源、制作物品、建造基地，解开星球生态系统的秘密。8月31日Steam试玩版上线，Gamescom展台试玩。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/1510440/Honeycomb_The_World_Beyond/",
      topicAngles: ["生物工程+生存沙盒的创新融合","Snail Games科幻生存游戏布局","Gamescom展后热度观察"]
    },
    {
      id: 204,
      name: "喵喵遗传学",
      nameEn: "Mewgenics",
      date: "2026-09-08",
      developer: "Edmund McMillen / Tyler Glaiel",
      publisher: "Nicalis",
      genres: ["回合制","Roguelike","策略","猫咪育种","独立"],
      genreClass: "strategy",
      platforms: ["PS5","Xbox","Switch 2"],
      price: "$39.99(约¥288)",
      chinese: false,
      hot: true,
      desc: "《以撒的结合》创作者Edmund McMillen打造的回合制Roguelike猫咪育种策略游戏。培育拥有独特基因组合的猫咪，组建队伍探索程序生成的世界。PC版已于2026年2月发售并获得极高评价，主机版终于登场。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/2657810/Mewgenics/",
      topicAngles: ["以撒之父新作：猫咪育种Roguelike的爆款基因","Mewgenics从PC到主机的跨平台扩展","独立游戏明星制作人的创作方法论"]
    },
    {
      id: 106,
      name: "英灵神殿",
      nameEn: "Valheim",
      date: "2026-09-09",
      developer: "Iron Gate AB",
      publisher: "Coffee Stain Publishing",
      genres: ["生存","开放世界"," crafting","多人合作","维京"],
      genreClass: "adventure",
      platforms: ["Switch 2"],
      price: "$19.99(约¥143)",
      chinese: true,
      hot: false,
      desc: "销量超1200万份的维京题材生存游戏正式登陆Switch 2。玩家将探索程序生成的炼狱世界，建造基地、打造武器、挑战北欧神话BOSS。Switch 2版支持本地多人联机。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/892970/Valheim/",
      topicAngles: ["Valheim登陆Switch 2：千万销量独立游戏的平台扩展","维京生存游戏的长尾效应分析"]
    },
    {
      id: 121,
      name: "地下城竞技场",
      nameEn: "Dungeon Brawls",
      date: "2026-09-09",
      developer: "Underground Cat",
      publisher: "Wise Games",
      genres: ["动作肉鸽","冒险","多人合作"],
      genreClass: "action",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "支持4人联机的动作肉鸽游戏。数十位可供选择的英雄，自由搭配上百种技能与遗物。玩家可叫上好友并肩作战，挑战敌潮，体验割草战斗的爽快感。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4246640/Dungeon_Brawls/",
      topicAngles: ["四人联机动作肉鸽游戏市场观察","割草类肉鸽游戏的玩法创新"]
    },
    {
      id: 144,
      name: "In Falsus",
      nameEn: "In Falsus",
      date: "2026-09-09",
      developer: "lowiro",
      publisher: "lowiro",
      genres: ["节奏","视觉小说","音乐","叙事"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "《Arcaea》开发商lowiro全新音乐节奏游戏，融合视觉小说叙事。收录70+首曲目(含40+首原创)，五条角色路线全日语配音，键鼠双轨道操作，五位互相关联主角视角探索近未来世界。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3971950/",
      topicAngles: ["Arcaea开发商lowiro新作：节奏×视觉小说融合","70+曲目的音乐游戏内容量评估","节奏游戏叙事化的创新方向"]
    },
    {
      id: 145,
      name: "东方红魔乡 新经典版",
      nameEn: "Touhou Koumakyou: New Classic - the Embodiment of Scarlet Devil",
      date: "2026-09-09",
      developer: "上海アリス幻樂団, 上海アリスReprise",
      publisher: "Alliance Arts",
      genres: ["弹幕射击","动作","独立"],
      genreClass: "shooter",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "东方系列经典作品《红魔乡》的重制版，ZUN全新重制原声音乐。操控博丽灵梦和雾雨魔理沙穿越弹幕完成红雾异变，东方粉丝社群关注度较高。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4659620/",
      topicAngles: ["东方红魔乡重制版：同人IP的正式化路径","ZUN亲自重制原声的音乐价值"]
    },
    {
      id: 156,
      name: "蛮族传奇：野兽大师",
      nameEn: "Barbarian Saga: The Beastmaster",
      date: "2026-09-09",
      developer: "Dormidin Studio",
      publisher: "Selecta Play",
      genres: ["动作冒险","奇幻","手绘","开放世界"],
      genreClass: "adventure",
      platforms: ["Steam","PS5","Xbox","Switch"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "手绘风格奇幻动作冒险游戏，扮演蛮族战士在充满野兽的开放世界中冒险。融合战斗、探索与生存元素，Selecta Play发行。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/2459840/Barbarian_Saga_The_Beastmaster/",
      topicAngles: ["手绘风格动作冒险游戏的视觉表现","蛮族题材奇幻游戏的市场定位"]
    },
    {
      id: 187,
      name: "宇宙恐惧",
      nameEn: "Cosmic Fear",
      date: "2026-09-09",
      developer: "Alessandro Guzzo",
      publisher: "Alessandro Guzzo",
      genres: ["恐怖","克苏鲁","心理恐怖","探索","科幻"],
      genreClass: "horror",
      platforms: ["Steam","Epic"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "第一人称宇宙恐怖冒险游戏。恐怖感不源自鬼屋，而是围绕外星现象、远古秘密、外星影响与军方阴谋不断扩大的谜团展开。Steam试玩版已上线。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3306920/Cosmic_Fear/",
      topicAngles: ["克苏鲁题材恐怖游戏持续热度观察","单人开发者的宇宙恐怖叙事探索"]
    },
    {
      id: 111,
      name: "地城拓荒",
      nameEn: "Dungeon Settlers",
      date: "2026-09-10",
      developer: "CanOpener",
      publisher: "CanOpener",
      genres: ["策略","模拟","殖民地建设","地牢探险"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "黑暗奇幻策略游戏，融合殖民地建设与地下城探险玩法（被称为RimWorld与Darkest Dungeon的邂逅）。作为探险队队长探索并征服地下城，建设据点、培养队员、进行战术战斗。Steam愿望单突破10万。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2798330/_Dungeon_Settlers/",
      topicAngles: ["殖民地建设+地牢探险混合品类创新","10万+愿望单独立策略游戏成功密码","黑暗奇幻策略游戏的玩法深度"]
    },
    {
      id: 114,
      name: "风火轮无限竞速",
      nameEn: "HOT WHEELS Infinite Rush",
      date: "2026-09-10",
      developer: "Milestone",
      publisher: "Milestone",
      genres: ["竞速","开放世界","街机","载具","多人"],
      genreClass: "action",
      platforms: ["Steam","PS5","Xbox","Switch 2"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "经典玩具车品牌风火轮推出的开放世界竞速游戏，玩家在巨大开放世界中驾驶风火轮标志性玩具车参与各种赛事与挑战。Milestone开发，延续街机风格竞速体验。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2821390/HOT_WHEELS_Infinite_Rush/",
      topicAngles: ["风火轮IP开放世界竞速的市场潜力","Milestone街机竞速游戏开发经验","玩具车竞速游戏的目标受众分析"]
    },
    {
      id: 122,
      name: "三国志14 威力加强传承版",
      nameEn: "Romance of the Three Kingdoms 14: Power Up Kit Legacy Edition",
      date: "2026-09-10",
      developer: "KOEI TECMO GAMES",
      publisher: "KOEI TECMO GAMES",
      genres: ["策略","历史模拟","战棋"],
      genreClass: "strategy",
      platforms: ["Steam","PS5","PS4","Switch"],
      price: "¥128(DLC)",
      chinese: true,
      hot: false,
      desc: "纪念《三国志》系列40周年的集大成版本。在威力加强版基础上追加谍报、侦察、巡视等军情系统，以及功勋培养、方策系统（72种策略）等新玩法。完整收录过往全部DLC。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/872410/_14/",
      topicAngles: ["三国志系列40周年纪念版本深度解析","历史策略游戏的长期运营策略","光荣特库摩三国IP发展之路"]
    },
    {
      id: 123,
      name: "幻世录 重制版",
      nameEn: "The Legend of Fancy Realm Remake",
      date: "2026-09-10",
      developer: "宇峻奥汀科技",
      publisher: "宇峻奥汀科技",
      genres: ["战棋","SRPG","奇幻","重制"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "经典异色战棋SRPG《幻世录》的高清重制版。以剧情为核心，将传统战棋策略与宏大的史诗叙事结合。正式版完整收录1998年经典版游戏，支持全语音配音。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/4030150/",
      topicAngles: ["经典国产战棋重制版情怀分析","幻世录IP的历史地位与现代价值","国产SRPG重制浪潮观察"]
    },
    {
      id: 124,
      name: "战狗",
      nameEn: "WARDOGS",
      date: "2026-09-10",
      developer: "BULKHEAD",
      publisher: "Team17",
      genres: ["第一人称射击","战术","多人","抢先体验"],
      genreClass: "shooter",
      platforms: ["Steam"],
      price: "¥149(抢先体验)",
      chinese: true,
      hot: true,
      desc: "全面战争式百人战术FPS，最高支持100名玩家在大规模军事沙盒中对战。融合战术枪战、诸兵种联合作战以及建造与破坏机制。Steam愿望单突破100万，9月最受期待Steam游戏榜首。开发商采用反向营销策略引发热议。",
      priority: "high",
      heatLevel: 5,
      officialUrl: "https://store.steampowered.com/app/1867240/WARDOGS/",
      topicAngles: ["100万愿望单：百人战术FPS黑马WARDOGS深度前瞻","反向营销十不买理由：独立游戏的话题营销新玩法","Team17发行的军事射击游戏市场表现预测"]
    },
    {
      id: 142,
      name: "欢迎来到埃尔德菲尔德",
      nameEn: "Welcome to Elderfield",
      date: "2026-09-10",
      developer: "Chris Cote",
      publisher: "Kwalee",
      genres: ["生活模拟","冒险","RPG","舒适恐怖"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "手绘风格的舒适恐怖RPG，融合农场经营、社交恋爱、谜团调查与怪物战斗。搭配暗色Lo-Fi音乐，在Elderfield小镇探索旧神与秘密，Steam愿望单约1.2万。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3195440/",
      topicAngles: ["舒适恐怖品类的融合创新观察","手绘风格独立RPG的差异化定位"]
    },
    {
      id: 172,
      name: "屏幕边界",
      nameEn: "Screenbound",
      date: "2026-09-10",
      developer: "Crescent Moon Games, Radical Forge",
      publisher: "Digital Pajamas, Crescent Moon Games",
      genres: ["动作冒险","平台解谜","独立"],
      genreClass: "adventure",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "独特的2D/3D双维度切换平台解谜游戏。用妈妈车库里找到的神秘设备控制周围世界，在2D像素游戏和3D世界之间无缝切换，战斗并解谜，揭开这个相互连接世界的神秘面纱。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2805070/Screenbound/",
      topicAngles: ["2D/3D维度切换的平台解谜创新","独立游戏Screenbound的玩法前瞻"]
    },
    {
      id: 173,
      name: "接管2",
      nameEn: "Takeover 2",
      date: "2026-09-10",
      developer: "Pelikan13",
      publisher: "Pelikan13",
      genres: ["动作","休闲","独立","街机"],
      genreClass: "action",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "经典街机风格动作游戏续作，快节奏战斗与关卡挑战。像素美术风格，简单上手但难于精通的操作体验。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4423270/Takeover_2/",
      topicAngles: ["街机动作游戏独立续作观察"]
    },
    {
      id: 174,
      name: "破碎传说：别说谎",
      nameEn: "BrokenLore: Don't Lie",
      date: "2026-09-10",
      developer: "Serafini Productions",
      publisher: "Wired Productions, Serafini Productions",
      genres: ["恐怖","动作冒险","心理恐怖"],
      genreClass: "horror",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "心理恐怖冒险游戏，探索被黑暗秘密笼罩的小镇。在谎言与真相之间抉择，你的每一个选择都将影响故事的走向。支持简繁中文。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3886200/BrokenLore_DONT_LIE/",
      topicAngles: ["心理恐怖游戏的叙事选择机制","Wired Productions发行的恐怖新作"]
    },
    {
      id: 184,
      name: "英雄传说：零之轨迹",
      nameEn: "The Legend of Heroes: Trails from Zero",
      date: "2026-09-10",
      developer: "Falcom",
      publisher: "NIS America",
      genres: ["回合制RPG","日式RPG","剧情","移植"],
      genreClass: "rpg",
      platforms: ["PS5","Switch 2"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "轨迹系列经典作品《零之轨迹》登陆PS5与Switch 2平台。玩家扮演克洛斯贝尔警察特别任务支援科的罗伊德，揭开克洛斯贝尔自治州背后的阴谋。支持高清画质升级。",
      priority: "low",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/1668510/The_Legend_of_Heroes_Trails_from_Zero/",
      topicAngles: ["轨迹系列经典作品主机移植","Falcom经典IP平台扩展策略"]
    },
    {
      id: 185,
      name: "英雄传说：碧之轨迹",
      nameEn: "The Legend of Heroes: Trails to Azure",
      date: "2026-09-10",
      developer: "Falcom",
      publisher: "NIS America",
      genres: ["回合制RPG","日式RPG","剧情","移植"],
      genreClass: "rpg",
      platforms: ["PS5","Switch 2"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "《零之轨迹》直接续篇登陆PS5与Switch 2。克洛斯贝尔篇完结之作，罗伊德与伙伴们面临更大的政治阴谋与危机。支持高清画质升级，轨迹系列粉丝必玩。",
      priority: "low",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/1668520/The_Legend_of_Heroes_Trails_to_Azure/",
      topicAngles: ["碧之轨迹：克洛斯贝尔篇的史诗完结","轨迹系列叙事巅峰之作重评"]
    },
    {
      id: 192,
      name: "NHL 27",
      nameEn: "NHL 27",
      date: "2026-09-11",
      developer: "EA Vancouver",
      publisher: "Electronic Arts",
      genres: ["体育","冰球","模拟"],
      genreClass: "simulation",
      platforms: ["PS5","Xbox"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "EA年度冰球模拟游戏。延续NHL系列经典的逼真冰球体验，更新球员数据与赛季内容。系列连续19年未登陆PC平台。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://www.ea.com/games/nhl/nhl-27",
      coverUrl: "https://s25.q4cdn.com/103200307/files/doc_multimedia/2026/7/1011320027/EA_NHL27_DLX_KeyArt_RGB_16-9_1920x1080.jpg",
      topicAngles: ["EA体育年货系列的市场表现与玩家疲劳","NHL系列为何19年拒绝PC平台"]
    },
    {
      id: 154,
      name: "云上叠叠乐",
      nameEn: "Cloudscrapers",
      date: "2026-09-14",
      developer: "Nementic Games",
      publisher: "Curve Games",
      genres: ["策略","资源管理","休闲","独立"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "极简资源管理策略游戏，建造不断攀升的摩天大楼。平衡资源、规划布局、应对挑战，以优雅的极简美学呈现城市建设策略体验。支持简体中文。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3562200/Cloudscrapers/",
      topicAngles: ["极简资源管理策略游戏的创新方向","Curve Games发行独立策略游戏观察"]
    },
    {
      id: 61,
      name: "漫威金刚狼",
      nameEn: "Marvel's Wolverine",
      date: "2026-09-15",
      developer: "Insomniac Games",
      publisher: "PlayStation Studios",
      genres: ["动作冒险","超级英雄","剧情"],
      genreClass: "action",
      platforms: ["PS5"],
      price: "$69.99(约¥398)",
      chinese: true,
      hot: true,
      desc: "《漫威蜘蛛侠》开发商Insomniac Games打造的PS5独占大作，以金刚狼为主角的M级硬核动作游戏。任务驱动线性叙事，战斗以近身肉搏为核心，完美还原艾德曼合金爪和自愈能力，引入三阶段怒火值系统和场景处决机制。琴·葛蕾、魔形女等变种人登场。",
      priority: "high",
      heatLevel: 5,
      officialUrl: "https://insomniac.games/",
      coverUrl: "https://image.api.playstation.com/vulcan/ap/rnd/202605/2221/2e98d11ecc5fc86cf404d0f4b7b4a1ba5774a51bf3db0020.jpg?w=1024",
      topicAngles: ["Insomniac漫威宇宙新篇章：金刚狼能否超越蜘蛛侠","PS5年度独占旗舰大作深度前瞻","超级英雄游戏从开放世界回归线性叙事的意义","金刚狼IP游戏化的历史与未来"]
    },
    {
      id: 104,
      name: "符文世界：龙之荒野",
      nameEn: "RuneScape: Dragonwilds",
      date: "2026-09-15",
      developer: "Jagex",
      publisher: "Jagex",
      genres: ["开放世界","生存","多人","奇幻"," crafting"],
      genreClass: "adventure",
      platforms: ["Steam","PS5","Xbox","Switch 2"],
      price: "$29.99(约¥218)",
      chinese: true,
      hot: true,
      desc: "经典MMORPG《RuneScape》IP衍生的开放世界生存游戏，1.0正式版脱离抢先体验。支持跨平台联机与专用服务器，融合RuneScape经典世界观与生存建造玩法，新增Switch 2版本。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/1374490/RuneScape_Dragonwilds/",
      topicAngles: ["经典MMORPG IP如何转型生存游戏","RuneScape Dragonwilds 1.0正式版内容盘点","跨平台+专用服务器的联机体验升级"]
    },
    {
      id: 107,
      name: "毁灭全人类2：重新探测",
      nameEn: "Destroy All Humans! 2: Reprobed",
      date: "2026-09-15",
      developer: "Black Forest Games",
      publisher: "THQ Nordic",
      genres: ["动作","开放世界","科幻","喜剧"],
      genreClass: "action",
      platforms: ["Switch 2"],
      price: "$39.99(约¥288)",
      chinese: false,
      hot: false,
      desc: "经典外星入侵喜剧动作游戏重制版登陆Switch 2。玩家扮演外星人Crypto，在1960年代地球使用高科技武器和超能力大闹人间，充满黑色幽默与恶搞元素。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/1797000/Destroy_All_Humans_2_Reprobed/",
      topicAngles: ["经典喜剧动作游戏Switch 2移植表现","外星人入侵题材的恶搞魅力"]
    },
    {
      id: 125,
      name: "调酒师模拟器",
      nameEn: "Mixed Spirits: Bartender Simulator",
      date: "2026-09-15",
      developer: "Rogue Duck Interactive",
      publisher: "Rogue Duck Interactive, Gamersky Games",
      genres: ["模拟经营","休闲","策略"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "自由调酒模拟游戏。玩家可根据酸、甜、苦、辣、清爽等属性自由组合鸡尾酒，从挑选杯型、基酒搭配到装饰点缀全部亲自动手。经营酒吧，通过个性化装饰展现风格，策划活动吸引客流。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3891400/_/",
      topicAngles: ["调酒模拟游戏的小众市场","酒吧经营+调酒玩法的融合创新"]
    },
    {
      id: 141,
      name: "迪姆雷斯",
      nameEn: "Dimraeth",
      date: "2026-09-15",
      developer: "Mudtek",
      publisher: "Mudtek",
      genres: ["动作RPG","像素","合作","奇幻"],
      genreClass: "rpg",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "支持1-8人联机的像素风奇幻RPG，提供8个种族和6个职业选择。探索古老大地、掌握元素战斗、建造据点，在战火摧残的Mirkea大地对抗腐化与黑暗。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/2402680/",
      topicAngles: ["1-8人联机像素RPG的玩法深度","种族与职业系统的Build构筑空间"]
    },
    {
      id: 166,
      name: "神庙岛之谜",
      nameEn: "Secrets of Temple Isle",
      date: "2026-09-15",
      developer: "Moses Doyle",
      publisher: "Moses Doyle",
      genres: ["动作RPG","探索","地牢探险","90年代怀旧"],
      genreClass: "rpg",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "90年代风格探索RPG，突袭致命地牢、洞穴与神庙获取装备和宝藏。在手工打造的多彩岛屿上进行战术第三人称战斗，发现远古传奇遗物，拯救岛屿免于迫近的威胁。单人独立开发多年之作。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/1842680/Secrets_of_Temple_Isle/",
      topicAngles: ["单人独立开发RPG的坚持与突破","90年代怀旧风格RPG的现代演绎"]
    },
    {
      id: 188,
      name: "TCG卡牌商店模拟器",
      nameEn: "TCG Card Shop Simulator",
      date: "2026-09-15",
      developer: "OPNeon Games",
      publisher: "OPNeon Games",
      genres: ["模拟经营","卡牌","管理"],
      genreClass: "simulation",
      platforms: ["Steam","PS5","Xbox","Switch","Switch 2"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "TCG卡牌商店经营模拟游戏1.0正式版。售卖卡包、设计店铺布局、整理货架，还可以自己开包收集稀有卡牌。1.0版本新增可游玩的Tetramon TCG对战系统与锦标赛模式。抢先体验近两年后正式发售，首发加入Xbox Game Pass。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3070070/TCG_Card_Shop_Simulator/",
      topicAngles: ["模拟经营品类持续火热：TCG商店模拟器的市场表现","卡牌收集+店铺经营双重玩法设计","抢先体验两年后的1.0正式版内容分析"]
    },
    {
      id: 193,
      name: "恐惧列车",
      nameEn: "Fright Train",
      date: "2026-09-15",
      developer: "WildArts Games",
      publisher: "Black Lantern Collective",
      genres: ["生存恐怖","惊悚","叙事"],
      genreClass: "horror",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "设定在列车上的生存恐怖游戏。玩家在一趟充满未知的旅程中面对各种超自然威胁，需要利用有限的资源和环境生存。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4132890/Fright_Train/",
      topicAngles: ["封闭空间恐怖游戏设计：列车题材的紧张感构建","独立恐怖游戏的叙事创新"]
    },
    {
      id: 203,
      name: "活性物质",
      nameEn: "Active Matter",
      date: "2026-09-15",
      developer: "Matter Team",
      publisher: "Gaijin Entertainment",
      genres: ["第一人称射击","战术","科幻","硬核","在线多人"],
      genreClass: "shooter",
      platforms: ["Steam","PS5","Xbox"],
      price: "$39.99(约¥288)",
      chinese: false,
      hot: false,
      desc: "硬核在线射击游戏，玩家扮演被困在时间循环中的特工，进入充满活性物质的量子不稳定区域。与来自其他时间线的对手战斗，在物理法则崩坏的异常现象中求生并收集资源。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2887580/Active_Matter/",
      topicAngles: ["时间循环+战术射击的玩法创新","Gaijin Entertainment硬核射击新作观察","不稳定多元宇宙设定的科幻FPS"]
    },
    {
      id: 152,
      name: "伊莫",
      nameEn: "Aniimo",
      date: "2026-09-16",
      developer: "Pawprint Studio",
      publisher: "Pawprint Studio",
      genres: ["开放世界","动作RPG","生物收集","免费"],
      genreClass: "rpg",
      platforms: ["Steam","PS5","Xbox"],
      price: "免费",
      chinese: true,
      hot: true,
      desc: "免费开放世界生物收集动作RPG，探索广袤大陆Idyll，与独特生物Aniimo缔结纽带解锁新能力，前往天空都市，与其他探路者展开竞技对战。跨平台联机，支持简繁中文。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/4126040/Aniimo/",
      topicAngles: ["免费开放世界生物收集RPG能否挑战宝可梦地位","跨平台联机生物收集游戏的市场潜力","Pawprint Studio新作F2P模式分析"]
    },
    {
      id: 62,
      name: "英雄传说：空之轨迹 the 2nd 重制版",
      nameEn: "The Legend of Heroes: Trails in the Sky the 2nd",
      date: "2026-09-17",
      developer: "Falcom",
      publisher: "Falcom",
      genres: ["回合制RPG","日式RPG","剧情"],
      genreClass: "rpg",
      platforms: ["Steam","PS5","Switch"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "经典JRPG《空之轨迹SC》完全重制版，继承前作「无缝切换战斗系统」，加入新连携攻击「勇猛突袭」。以艾丝蒂尔寻找约修亚的旅程为主线，轨迹系列粉丝必玩之作。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/4225980/Trails_in_the_Sky_2nd_Chapter/",
      topicAngles: ["轨迹系列经典重制的情怀与创新","日式RPG重制版市场观察"]
    },
    {
      id: 89,
      name: "火焰纹章 万缕千丝",
      nameEn: "Fire Emblem: Fortune's Weave",
      date: "2026-09-17",
      developer: "Intelligent Systems",
      publisher: "任天堂",
      genres: ["战棋","SRPG","策略","奇幻"],
      genreClass: "strategy",
      platforms: ["Switch 2"],
      price: "HK$499(约¥430)",
      chinese: true,
      hot: true,
      desc: "《火焰纹章》系列最新正统续作，Switch 2独占发售。完整职业系统与深度策略战棋玩法，任天堂直面会已公布完整职业体系。经典战棋IP在Switch 2上的首款独占大作。",
      priority: "high",
      heatLevel: 5,
      officialUrl: "https://www.nintendo.com/",
      coverUrl: "https://www.nintendo.com/eu/media/images/assets/nintendo_switch_2_games/fireemblemfortunesweave/16x9_NSwitch2_FireEmblemFortunesWeave_image1600w.jpg",
      topicAngles: ["火焰纹章Switch 2独占的战略意义","经典战棋IP在2026年的进化方向","任天堂第一方Switch 2阵容深度分析"]
    },
    {
      id: 112,
      name: "战锤40K：战争黎明4",
      nameEn: "Warhammer 40,000: Dawn of War IV",
      date: "2026-09-17",
      developer: "KING Art",
      publisher: "Deep Silver",
      genres: ["即时战略","战锤40K","科幻","多人"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "¥258(标准版)",
      chinese: true,
      hot: true,
      desc: "经典即时战略系列回归，指挥四大战锤40K阵营（含首次登场的机械修会），超过70个史诗战役任务。Black Library作家打造剧情，支持单人/合作通关，扩展Sync Kill系统带来残酷战斗演出。Steam愿望单超8.6万。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/2272360/Warhammer_40000_Dawn_of_War_IV/",
      topicAngles: ["战锤40K RTS经典系列回归","四大阵营+机械修会新势力解析","70+战役任务的内容量评估","即时战略游戏在2026年的复兴迹象"]
    },
    {
      id: 140,
      name: "另一个伊甸：起源",
      nameEn: "Another Eden Begins",
      date: "2026-09-17",
      developer: "WRIGHT FLYER STUDIOS",
      publisher: "WRIGHT FLYER STUDIOS",
      genres: ["回合制RPG","时间旅行","剧情","日式RPG"],
      genreClass: "rpg",
      platforms: ["Steam","Switch","Switch 2"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "由《超时空之钥》等经典RPG创作者加藤正人主导的时间旅行RPG，支持New Game+。携带升级角色展开新冒险，发现超过10种不同结局，移动端人气JRPG登陆主机与PC。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4163960/",
      topicAngles: ["加藤正人时间旅行RPG登陆主机PC","移动端JRPG移植策略观察","New Game+与多结局的叙事深度"]
    },
    {
      id: 153,
      name: "无尽帝国2",
      nameEn: "ENDLESS Legend 2",
      date: "2026-09-17",
      developer: "AMPLITUDE Studios",
      publisher: "Hooded Horse",
      genres: ["4X策略","回合制","奇幻","帝国经营"],
      genreClass: "strategy",
      platforms: ["Steam","PS5","Xbox"],
      price: "$49.99(约¥358)",
      chinese: true,
      hot: true,
      desc: "4X奇幻策略游戏1.0正式版脱离抢先体验。领导非对称阵营，在濒临灭绝的海洋世界上建立帝国、运用政治影响、组建大军，发掘埋藏于星球深处的黑暗秘密。支持简繁中文。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/3407390/ENDLESS_Legend_2/",
      topicAngles: ["无尽帝国2 1.0正式版内容盘点","AMPLITUDE工作室4X策略进化","Hooded Horse发行策略游戏布局"]
    },
    {
      id: 167,
      name: "三位一体6：时空共旅",
      nameEn: "Trine 6: Together in Time",
      date: "2026-09-17",
      developer: "Frozenbyte",
      publisher: "Cooldown Games",
      genres: ["解谜平台","合作","奇幻","冒险"],
      genreClass: "adventure",
      platforms: ["Steam","Epic","PS5","Xbox","Switch","Switch 2"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "经典合作解谜平台系列第六部正统续作。支持1-4人合作（本地/在线），以时空旅行为主题的全新奇幻冒险。凭借智慧、时机与协作解开谜题，对抗狡猾生物，穿越危险道路。支持简繁中文。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/2932260/Trine_6_Together_in_Time/",
      topicAngles: ["三位一体系列第六部：合作解谜平台的进化","时空旅行主题的关卡设计创新","1-4人合作模式的社交游戏魅力"]
    },
    {
      id: 175,
      name: "黑木",
      nameEn: "BLACKWOOD",
      date: "2026-09-17",
      developer: "AttritoM7 Productions",
      publisher: "IZilla Games, AttritoM7 Productions",
      genres: ["动作冒险","RPG","策略","黑暗奇幻"],
      genreClass: "action",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "黑暗奇幻动作冒险RPG，在充满危险的黑木森林中探索与战斗。融合策略元素的动作系统，非线性叙事与多结局设计。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3639070/BLACKWOOD/",
      topicAngles: ["黑暗奇幻独立RPG的叙事探索"]
    },
    {
      id: 189,
      name: "行会：欧罗巴1410",
      nameEn: "The Guild: Europa 1410",
      date: "2026-09-17",
      developer: "Ashborne Games",
      publisher: "THQ Nordic",
      genres: ["策略","历史模拟","经营","抢先体验"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "《行会》系列回归初心之作。在中世纪欧洲以小本家庭生意起步，通过世代经营扩张家族影响力，管理继承人与家族王朝。融合经济模拟、政治权谋与社交互动。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2977260/The_Guild__Europa_1410/",
      topicAngles: ["经典模拟策略系列回归：行会系列的历史与传承","中世纪欧洲家族经营模拟的玩法深度","THQ Nordic中等预算策略游戏发行策略"]
    },
    {
      id: 194,
      name: "核心之心",
      nameEn: "Kernel Hearts",
      date: "2026-09-17",
      developer: "Ephemera Games",
      publisher: "Whitethorn Games",
      genres: ["动作RPG","Roguelike","冒险"],
      genreClass: "rpg",
      platforms: ["Steam","PS5","Xbox","Switch 2"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "动作RPG与Roguelike融合的游戏。在程序生成的世界中战斗、探索与成长，融合快节奏动作战斗与永久死亡机制。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/2902170/Kernel_Hearts/",
      topicAngles: ["动作RPG+Roguelike品类的市场饱和度观察","Whitethorn Games发行独立游戏策略"]
    },
    {
      id: 176,
      name: "姆明：冬日的温暖",
      nameEn: "Moomintroll: Winter's Warmth",
      date: "2026-09-18",
      developer: "Hyper Games",
      publisher: "Hyper Games, Kakehashi Games",
      genres: ["冒险","RPG","治愈","独立"],
      genreClass: "adventure",
      platforms: ["Steam","Switch 2","PS5"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "基于经典姆明IP改编的治愈冒险游戏。在姆明谷的冬日中探索、交友、解谜，体验温馨的北欧童话世界。支持简繁中文，适合全年龄段玩家。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3256150/Moomintroll_Winters_Warmth/",
      topicAngles: ["经典IP姆明的游戏化改编","治愈系冒险游戏的市场表现"]
    },
    {
      id: 195,
      name: "行尸走肉：生存街道",
      nameEn: "The Walking Dead: Streets of Survival",
      date: "2026-09-18",
      developer: "Odaclick Game Studio",
      publisher: "Trailmark Games",
      genres: ["清版动作","合作","丧尸"],
      genreClass: "action",
      platforms: ["Steam","PS5","Xbox","Switch 2","Switch"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "《行尸走肉》IP改编的清版动作游戏。在丧尸末世中与朋友并肩作战，体验爽快的横版清版格斗与丧尸屠杀。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3777850/The_Walking_Dead_Streets_of_Survival/",
      topicAngles: ["行尸走肉IP改编游戏的品类选择：清版动作是否合适","丧尸题材清版动作游戏的市场潜力","IP授权游戏的独立开发模式"]
    },
    {
      id: 177,
      name: "裁缝师",
      nameEn: "Dressmaker",
      date: "2026-09-21",
      developer: "Cozy Lives",
      publisher: "Free Lives",
      genres: ["休闲","模拟","创造"],
      genreClass: "simulation",
      platforms: ["Steam","Mac","Linux"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "温馨治愈的裁缝模拟游戏，设计并缝制独一无二的服装。从选布料到裁剪缝纫，完成客户订单，打造属于自己的时装品牌。支持简繁中文。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4019220/Dressmaker/",
      topicAngles: ["裁缝模拟游戏的治愈体验","Free Lives发行的休闲模拟新作"]
    },
    {
      id: 105,
      name: "沙丘：觉醒",
      nameEn: "Dune: Awakening",
      date: "2026-09-22",
      developer: "Funcom",
      publisher: "Funcom",
      genres: ["开放世界","生存","多人","科幻","MMO"],
      genreClass: "adventure",
      platforms: ["Steam","PS5","Xbox"],
      price: "$49.99(约¥358)",
      chinese: true,
      hot: true,
      desc: "基于弗兰克·赫伯特《沙丘》宇宙打造的开放世界生存MMO，玩家在被放逐到厄拉科斯星球后必须学会生存。融合基地建造、载具战斗、政治阴谋与大型多人冲突，支持千人同屏沙暴攻城战。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/1172710/Dune_Awakening/",
      topicAngles: ["沙丘IP开放世界生存MMO的市场潜力","千人沙暴攻城战的技术实现","Funcom生存游戏开发经验再验证"]
    },
    {
      id: 178,
      name: "海岸",
      nameEn: "Rivage",
      date: "2026-09-22",
      developer: "待确认",
      publisher: "待确认",
      genres: ["冒险","探索","独立"],
      genreClass: "adventure",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "氛围感强烈的探索冒险游戏，在神秘的海岸线展开旅程。独特的视觉风格与沉浸式音效，探索未知地域的秘密。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4094660/Rivage/",
      topicAngles: ["氛围探索游戏的独特魅力"]
    },
    {
      id: 63,
      name: "控制：共振",
      nameEn: "Control: Resonant",
      date: "2026-09-24",
      developer: "Remedy Entertainment",
      publisher: "505 Games",
      genres: ["动作冒险","超自然","射击"],
      genreClass: "action",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "斩获多项大奖的《控制》正统续作，与迪伦一同探索广阔的腐化都市，直面混沌希斯、侵入性微生物「霉菌」等超自然威胁。Remedy「连接宇宙」重要作品。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/3669870/CONTROL_Resonant/",
      topicAngles: ["控制续作前瞻：超自然动作游戏的新高度","Remedy连接宇宙布局深度解析","9月24日双雄对决：控制vs寂静岭"]
    },
    {
      id: 64,
      name: "寂静岭：小镇陷落",
      nameEn: "Silent Hill: Townfall",
      date: "2026-09-24",
      developer: "No Code / Annapurna Interactive",
      publisher: "Konami",
      genres: ["心理恐怖","冒险","解谜"],
      genreClass: "horror",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: false,
      hot: true,
      desc: "科乐美寂静岭IP复兴重要作品，故事设定在1996年苏格兰，带来独特的冷寂心理恐怖氛围。第一人称视角，无战斗系统，核心为潜行、躲避和逃亡，使用CRTV便携电视等工具探索。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/1636440/SILENT_HILL_Townfall/",
      topicAngles: ["寂静岭IP复兴之路：从P.T.到Townfall","心理恐怖游戏的叙事与氛围营造","9月24日双雄对决：恐怖vs动作"]
    },
    {
      id: 138,
      name: "加菲猫：逃离星期一",
      nameEn: "Garfield - Escape from Monday",
      date: "2026-09-24",
      developer: "OSome Studio",
      publisher: "Microids",
      genres: ["3D平台","动作冒险","喜剧"],
      genreClass: "adventure",
      platforms: ["Steam","PS5","Xbox","Switch"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "加菲猫主题3D平台动作游戏，在满是蔬菜的噩梦世界中冒险，唤醒沉睡中的加菲猫逃离这场噩梦。Microids发行的休闲合家欢作品。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3932790/Garfield__Escape_from_Monday/",
      topicAngles: ["加菲猫IP改编3D平台游戏的市场定位","合家欢休闲动作游戏的受众分析"]
    },
    {
      id: 139,
      name: "王国保卫战6：新启程",
      nameEn: "Kingdom Rush 6: Genesis",
      date: "2026-09-24",
      developer: "Ironhide Game Studio",
      publisher: "Ironhide Game Studio",
      genres: ["塔防","策略","奇幻"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "经典塔防系列第六部正统续作，迎来系列15周年纪念。穿越时间回到王国更早的年代，建造防御塔、指挥英雄，阻止卫兹南踏上魔道，改变魔王降世的命运。Steam试玩版已开放，新增经典模式致敬初代。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/4259190/",
      topicAngles: ["王国保卫战15周年：经典塔防IP回归","经典模式致敬初代的情怀设计","塔防游戏长线运营与品类生命力"]
    },
    {
      id: 179,
      name: "牧场物语：特拉迪亚的回声",
      nameEn: "Harvest Moon: Echoes of Teradea",
      date: "2026-09-24",
      developer: "Natsume",
      publisher: "Natsume",
      genres: ["模拟经营","农场","生活模拟","RPG"],
      genreClass: "simulation",
      platforms: ["Switch","Switch 2"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "经典牧场经营系列最新作，在特拉迪亚大陆经营农场、结交村民、探索秘境。延续系列经典的种田、畜牧、恋爱与节日系统，带来全新的故事与角色。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://www.natsume.com/",
      coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/ar5ufs.jpg",
      topicAngles: ["牧场物语系列最新作前瞻","经典农场模拟IP的现代进化"]
    },
    {
      id: 75,
      name: "EA Sports FC 27",
      nameEn: "EA Sports FC 27",
      date: "2026-09-25",
      developer: "EA Vancouver",
      publisher: "EA Sports",
      genres: ["体育","足球","模拟"],
      genreClass: "simulation",
      platforms: ["Steam","PS5","Xbox","Switch 2"],
      price: "¥248",
      chinese: true,
      hot: true,
      desc: "EA年度足球模拟游戏最新作，改进HyperMotionV技术，增强球员触球真实感。新增女子职业俱乐部模式与扩展的终极球队内容，PC版首次达到与主机版同等规格。",
      priority: "medium",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/4080220/EA_SPORTS_FC_27/",
      topicAngles: ["FC 27技术升级与玩法改进盘点","年货足球游戏的创新瓶颈与突破"]
    },
    {
      id: 76,
      name: "尼瓦利斯之夜",
      nameEn: "Nivalis Nights",
      date: "2026-09-29",
      developer: "Ion Lands",
      publisher: "505 Games",
      genres: ["生活模拟","赛博朋克","经营"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "赛博朋克风格生活模拟游戏，在云端城市尼瓦利斯经营自己的餐厅与住所。接取任务、结识角色、探索城市秘密，体验独特的霓虹美学与慢节奏生活。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/1488490/Nivalis_Nights/",
      topicAngles: ["赛博朋克生活模拟的差异化定位","Ion Lands云端朋克美学风格解析"]
    },
    {
      id: 180,
      name: "Toem 2",
      nameEn: "TOEM 2",
      date: "2026-09-29",
      developer: "Something We Made",
      publisher: "Something We Made, popagenda",
      genres: ["冒险","休闲","解谜","摄影"],
      genreClass: "adventure",
      platforms: ["Steam","PS5","Switch"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "获奖摄影冒险游戏续作，踏上全新的黑白手绘风格旅程。用相机捕捉世界的美好瞬间，解开谜题，帮助旅途中遇到的各种角色。支持简繁中文。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2900640/TOEM_2/",
      topicAngles: ["Toem 2：摄影冒险游戏的续作进化","黑白手绘美术风格的独立游戏魅力"]
    },
    {
      id: 190,
      name: "狩猎之道2",
      nameEn: "Way of the Hunter 2",
      date: "2026-09-29",
      developer: "Nine Rocks Games",
      publisher: "THQ Nordic",
      genres: ["狩猎模拟","射击","开放世界","合作"],
      genreClass: "simulation",
      platforms: ["Steam","PS5","Xbox"],
      price: "$39.99(约¥288)",
      chinese: false,
      hot: false,
      desc: "狩猎模拟游戏1.0正式版，离开抢先体验。新增非洲基利马亚保护区与北美新劳伦提亚地图，搭载Zeiss、Bushnell、Bergara等正版授权狩猎装备，支持多人合作模式。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2543830/Way_of_the_Hunter_2/",
      topicAngles: ["硬核狩猎模拟游戏市场观察","正版装备授权在模拟游戏中的价值","抢先体验到正式版的运营策略"]
    },
    {
      id: 65,
      name: "我的世界：地下城2",
      nameEn: "Minecraft Dungeons II",
      date: "2026-09-30",
      developer: "Mojang Studios / Double Eleven",
      publisher: "Xbox Game Studios",
      genres: ["动作RPG","地牢探险","合作"],
      genreClass: "rpg",
      platforms: ["Steam","PS5","Xbox","Switch 2"],
      price: "¥148(标准版)",
      chinese: true,
      hot: true,
      desc: "「方块版暗黑破坏神」正统续作，探索前所未见的场景，支持多人合作冒险。全新职业、装备系统与关卡设计，进一步深化刷宝与Build构筑乐趣。",
      priority: "medium",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/1912410/Minecraft_Dungeons_II/",
      topicAngles: ["我的世界IP扩展：从沙盒到动作RPG","休闲向刷宝游戏的市场定位","全平台发售的合家欢游戏潜力"]
    },
    {
      id: 181,
      name: "墓地季节",
      nameEn: "Grave Seasons",
      date: "2026-09-30",
      developer: "Perfect Garbage",
      publisher: "Blumhouse Games, Solo Game",
      genres: ["模拟","RPG","恐怖","独立"],
      genreClass: "simulation",
      platforms: ["Steam","PS5","Xbox","Switch"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "融合农场模拟与谋杀悬疑的独特游戏。白天经营农场、结交邻居，夜晚调查小镇上发生的连环谋杀案。每个季节都有新的受害者，你需要找出隐藏在平凡日常中的凶手。Blumhouse Games发行。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3255110/Grave_Seasons/",
      topicAngles: ["农场模拟+谋杀悬疑的独特融合","Blumhouse Games进军游戏发行"]
    },
    {
      id: 182,
      name: "希曼与宇宙巨人：毁灭龙珠",
      nameEn: "He-Man: Dragon Pearl of Destruction",
      date: "2026-09-30",
      developer: "Bitmap Bureau",
      publisher: "Limited Run Games",
      genres: ["动作","街机","横版","经典IP"],
      genreClass: "action",
      platforms: ["Steam","PS5","PS4","Xbox","Switch"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "经典动画IP《宇宙巨人希曼》改编的横版动作游戏。操控希曼与骷髅王等经典角色，在埃坦尼亚王国展开冒险。复古街机风格，像素美术致敬经典。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3749580/HeMan_and_the_Masters_of_the_Universe_Dragon_Pearl_of_Destruction/",
      topicAngles: ["经典动画IP希曼的游戏化","复古街机动作游戏的情怀市场"]
    },
    {
      id: 183,
      name: "无处可逃",
      nameEn: "Nowhere",
      date: "2026-09-30",
      developer: "Midnight Forge LTD",
      publisher: "Midnight Forge LTD",
      genres: ["恐怖","冒险","北欧神话","叙事"],
      genreClass: "horror",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "北欧神话灵感叙事恐怖游戏，讲述诸神黄昏后北欧诸神的命运。融合侦探玩法与北欧恐怖美学，在黄金崇拜时代终结后的世界中展开调查。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/2743260/Nowhere/",
      topicAngles: ["北欧神话恐怖游戏的叙事探索","诸神黄昏后的世界观构建"]
    },
    {
      id: 191,
      name: "格林默维克之歌",
      nameEn: "Songs of Glimmerwick",
      date: "2026-09-30",
      developer: "Eastshade Studios",
      publisher: "Eastshade Studios",
      genres: ["冒险","RPG","奇幻","音乐"],
      genreClass: "adventure",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "魔法森林奇幻RPG，设定在女巫学院。施展法术如同演奏一首歌曲，上课、种植大学花园、交友并探索岛屿秘密。《Eastshade》开发商新作，支持中文，Steam试玩版已上线。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/1706510/Songs_of_Glimmerwick/",
      topicAngles: ["音乐魔法系统：法术与演奏融合的创新设计","Eastshade Studios从步行模拟到RPG的转型","独立奇幻RPG的叙事与探索设计"]
    },
    {
      id: 100,
      name: "真三国无双2 with 猛将传 Remastered",
      nameEn: "DYNASTY WARRIORS 3: Complete Edition Remastered",
      date: "2026-10-01",
      developer: "Koei Tecmo (光荣特库摩)",
      publisher: "Koei Tecmo",
      genres: ["动作","无双","三国","复刻"],
      genreClass: "action",
      platforms: ["Steam","PS5","Xbox","Switch 2"],
      price: "¥198",
      chinese: true,
      hot: true,
      desc: "经典无双系列奠基之作完全复刻，虚幻5引擎重现40+名武将与经典战场。动作系统全面升级，收录本体与猛将传全部内容，首次支持双人同屏作战。系列首部销量破百万的里程碑作品，支持中文配音。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/3841510/2_with__Remastered/",
      topicAngles: ["无双系列起源之作UE5复刻前瞻","光荣经典IP复刻策略与市场表现","真三国无双系列20年进化史"]
    },
    {
      id: 137,
      name: "雷曼传奇：重述",
      nameEn: "Rayman Legends Retold",
      date: "2026-10-01",
      developer: "Ubisoft Montpellier / Ubisoft Milan",
      publisher: "Ubisoft",
      genres: ["平台跳跃","动作冒险","横版","合作"],
      genreClass: "action",
      platforms: ["Steam","Epic","PS5","Xbox","Switch 2"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "育碧用Snowdrop引擎重制的《雷曼传奇》全3D演绎之作，迎来系列30周年。当阴影反派将腐化扩散至碎梦林地，玩家在快节奏横版冒险中穿越迷人世界，新增全新故事、反派与首次配音角色，附赠《雷曼起源增强版》，支持4人本地联机。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/4084710/Rayman_Legends_Retold/",
      topicAngles: ["雷曼系列30周年：经典平台IP全3D重制","Snowdrop引擎打造横版冒险的技术表现","育碧经典IP复兴策略与市场预期"]
    },
    {
      id: 101,
      name: "皇牌空战8：希孚之翼",
      nameEn: "ACE COMBAT 8: WINGS OF THEVE",
      date: "2026-10-02",
      developer: "Bandai Namco (万代南梦宫)",
      publisher: "Bandai Namco",
      genres: ["飞行射击","空战","街机","剧情"],
      genreClass: "shooter",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "皇牌空战系列时隔七年的正统续作，虚幻5引擎打造，支持光线追踪与DLSS。PC版最低需RTX 2060，延续系列标志性的电影化空战叙事与紧张刺激的飞行战斗。预购玩家可于9月28日提前解锁。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/2288340/ACE_COMBAT_8_WINGS_OF_THEVE/",
      topicAngles: ["皇牌空战系列时隔七年回归","空战街机游戏PC配置门槛分析","万代南梦宫经典IP续作策略"]
    },
    {
      id: 102,
      name: "战争机器：事变日",
      nameEn: "Gears of War: E-Day",
      date: "2026-10-06",
      developer: "The Coalition",
      publisher: "Xbox Game Studios",
      genres: ["第三人称射击","动作","科幻","战争"],
      genreClass: "shooter",
      platforms: ["Steam","Xbox"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "《战争机器》系列前传，以马可斯·菲利视角体验事变日的残酷与恐怖。虚幻5从底层构建，PC版支持光追及DLSS 4.5，首发加入Xbox Game Pass。8月6日已开启多人公测，预购与PC Game Pass用户可抢先体验。",
      priority: "high",
      heatLevel: 5,
      officialUrl: "https://store.steampowered.com/app/3010850/Gears_of_War_EDay/",
      topicAngles: ["战争机器系列前传：事变日的故事源起","虚幻5+光追+DLSS 4.5：PC版技术前瞻","Xbox旗舰登陆Steam的发行策略","8月公测热度与正式发售期待值分析"]
    },
    {
      id: 136,
      name: "星球大战：银河竞速",
      nameEn: "STAR WARS: Galactic Racer",
      date: "2026-10-06",
      developer: "Fuse Games",
      publisher: "Secret Mode",
      genres: ["竞速","Roguelite","动作","科幻"],
      genreClass: "action",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "以星球大战外环星域为背景的竞速Roguelite游戏。帝国瓦解后地下赛车联盟银河联赛崛起，辛迪加资助混乱赛道，玩家在法外之地竞速争夺冠军。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/4078430/",
      topicAngles: ["星战IP试水竞速Roguelite新品类","Secret Mode发行独立竞速游戏观察","外环星域地下赛车世界观设定解析"]
    },
    {
      id: 133,
      name: "银松镇",
      nameEn: "Silver Pines",
      date: "2026-10-08",
      developer: "Wych Elm",
      publisher: "Team17",
      genres: ["生存恐怖","类银河战士恶魔城","解谜","动作"],
      genreClass: "horror",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "设定在美国小镇的生存恐怖类银河战士恶魔城游戏。私家侦探Red Walker追查失踪音乐家Eddie Velvet，在半荒废的银松镇对抗噩梦般的存在，谨慎管理稀缺资源。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2333000/",
      topicAngles: ["生存恐怖×银河城：融合品类的创新空间","Team17发行独立恐怖游戏的产品线观察","稀缺资源管理对恐怖游戏节奏的影响"]
    },
    {
      id: 134,
      name: "养鬼吃人：复苏",
      nameEn: "Clive Barker's Hellraiser: Revival",
      date: "2026-10-08",
      developer: "Saber Interactive",
      publisher: "Saber Interactive",
      genres: ["恐怖","第一人称","生存","动作"],
      genreClass: "horror",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "经典恐怖系列全新篇章，第一人称动作恐怖生存游戏。玩家操控创世之谜盒的力量，与标志性的钉子头达成交易以求生存，延续克里夫·巴克标志性的恐怖美学。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/1551980/",
      topicAngles: ["养鬼吃人IP改编游戏的恐怖美学传承","第一人称生存恐怖的新作观察","Saber Interactive恐怖游戏产品线"]
    },
    {
      id: 135,
      name: "王国之心 合集",
      nameEn: "KINGDOM HEARTS Collection [I~III]",
      date: "2026-10-08",
      developer: "Square Enix",
      publisher: "Square Enix",
      genres: ["动作RPG","合集","迪士尼","剧情"],
      genreClass: "collection",
      platforms: ["PS5","Switch 2","Xbox"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "《王国之心》系列全三章合集首次以实体形式登陆PS5、Switch 2和Xbox，收录HD 1.5+2.5 ReMIX及HD 2.8 Final Chapter Prologue等作品，方便新老玩家一次性体验系列完整冒险，确认支持简繁中文。Nintendo Direct正式公布。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://www.square-enix.com/kingdomhearts/collection/en-us/",
      coverUrl: "https://fyre.cdn.sewest.net/kingdom-hearts-steam/6631ca2d5a1a8ff866ee1753/kh-all-FVsghm0KI.jpg",
      topicAngles: ["王国之心全系列合集登陆Switch 2的战略意义","Square Enix经典IP合集发行策略观察","实体版回归对收藏向玩家的价值"]
    },
    {
      id: 131,
      name: "永冻纪元",
      nameEn: "Permafrost",
      date: "2026-10-09",
      developer: "SpaceRocket Games",
      publisher: "Toplitz Productions",
      genres: ["生存","开放世界","合作","沙盒"],
      genreClass: "adventure",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "公元2035年末日浩劫将世界变为冰封荒原。玩家独自或最多4人合作，在广阔开放世界中探索、搜刮、制造、建造庇护所网络，在严寒中求生。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2254990/",
      topicAngles: ["冰封末日生存沙盒的差异化竞争","4人合作生存建造玩法深度","Toplitz发行生存游戏的产品线观察"]
    },
    {
      id: 132,
      name: "龙之信条2：黑暗觉者",
      nameEn: "Dragon's Dogma 2: Dark Arisen Expansion",
      date: "2026-10-09",
      developer: "Capcom",
      publisher: "Capcom",
      genres: ["动作RPG","开放世界","DLC","黑暗奇幻"],
      genreClass: "rpg",
      platforms: ["Steam","PS5","Xbox","Switch 2"],
      price: "$29.99(DLC)",
      chinese: true,
      hot: true,
      desc: "卡普空《龙之信条2》首个大型资料片黑暗觉者，新增超过25小时内容，包括新故事、地下城与硬核模式。Switch 2版为完整合包(本体+DLC)，现有玩家可单独购买DLC，支持60帧优化。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/2593290/Dragons_Dogma_2_Dark_Arisen_Expansion/",
      topicAngles: ["龙之信条2首个大型DLC内容深度解析","Switch 2完整合包首发：卡普空主机策略","硬核模式对动作RPG挑战性的提升"]
    },
    {
      id: 196,
      name: "纸面战",
      nameEn: "PAPERHEAD",
      date: "2026-10-09",
      developer: "Paperhead Team",
      publisher: "HypeTrain Digital",
      genres: ["复古FPS","射击","复古"],
      genreClass: "shooter",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "复古风格Boomer Shooter。原定9月18日发售，后延期至10月9日。以独特的纸面美术风格呈现快节奏射击体验，开发商表示需要更多时间打磨质量。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/2680280/PAPERHEAD/",
      topicAngles: ["Boomer Shooter品类持续热度观察","纸面美术风格在FPS中的独特应用","独立游戏延期策略与玩家期望管理"]
    },
    {
      id: 130,
      name: "动物园之星2",
      nameEn: "Planet Zoo 2",
      date: "2026-10-13",
      developer: "Frontier Developments",
      publisher: "Frontier Developments",
      genres: ["模拟经营","建造","管理","动物园"],
      genreClass: "simulation",
      platforms: ["Steam","Epic","PS5","Xbox"],
      price: "$49.99(标准版)",
      chinese: true,
      hot: true,
      desc: "Frontier打造的新一代动物园模拟游戏，首次引入水族馆和鸟舍系统。玩家可建造环球特色动物园，守护陆生、水生与飞行物种，将动物放归广袤野生动物保护区，支持跨平台创意工坊。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/3219030/Planet_Zoo_2/",
      topicAngles: ["动物园之星续作：水族馆与鸟舍系统革新","Frontier跨平台创意工坊的生态布局","模拟经营游戏的世代技术跃升"]
    },
    {
      id: 127,
      name: "越过山丘",
      nameEn: "over the hill",
      date: "2026-10-14",
      developer: "Funselektor Labs Inc., Strelka Games",
      publisher: "Funselektor Labs Inc.",
      genres: ["越野驾驶","冒险","合作","休闲"],
      genreClass: "adventure",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "《art of rally》开发商Funselektor Labs联合Strelka Games打造的1-4人越野探索游戏。驾驶60至80年代经典4x4越野车，独自或与朋友穿越崎岖山径与壮丽景色，体验越野运动黄金时代。Steam试玩版吸引超50万玩家。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/2929250/over_the_hill/",
      topicAngles: ["art of rally开发商新作：越野探索游戏前景","50万试玩玩家：独立驾驶游戏的热度密码","1-4人合作越野的社交体验设计"]
    },
    {
      id: 128,
      name: "不朽遗志",
      nameEn: "Valor Mortis",
      date: "2026-10-14",
      developer: "One More Level",
      publisher: "Lyrical Games, One More Level",
      genres: ["第一人称","类魂","动作RPG","黑暗奇幻"],
      genreClass: "action",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: false,
      hot: true,
      desc: "《幽灵行者》开发商One More Level全新第一人称类魂动作游戏。玩家化身拿破仑军队前士兵死而复生，掌握超自然力量对抗恐怖怪物，揭露威胁全人类的阴谋。法国影星文森特·卡索为拿破仑配音，首发加入Xbox Game Pass，由原定9月24日延期至10月14日。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/2828710/Valor_Mortis/",
      topicAngles: ["幽灵行者开发商新作：第一人称类魂创新","文森特·卡索配音拿破仑的叙事野心","延期避战9月档期：发售策略分析"]
    },
    {
      id: 129,
      name: "魔女面包店",
      nameEn: "The Witch's Bakery",
      date: "2026-10-14",
      developer: "Sunny Lab",
      publisher: "Silver Lining Interactive",
      genres: ["生活模拟","冒险","RPG","治愈"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "在巴黎经营魔法面包店的2D冒险RPG。管理店铺、探访标志性街道，用魔法牛角包治愈人们的心灵，温馨治愈的像素艺术风格。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/2967950/",
      topicAngles: ["魔法面包店：治愈系生活模拟的差异化","巴黎街头经营冒险的玩法融合"]
    },
    {
      id: 126,
      name: "恶魔城：贝尔蒙特的诅咒",
      nameEn: "Castlevania: Belmont's Curse",
      date: "2026-10-15",
      developer: "Konami / Evil Empire",
      publisher: "Konami",
      genres: ["类银河战士恶魔城","动作","动作RPG","黑暗奇幻"],
      genreClass: "action",
      platforms: ["Steam","PS5","Xbox","Switch"],
      price: "$29.99(标准版)",
      chinese: true,
      hot: true,
      desc: "《恶魔城》系列40周年纪念作品，Konami联手《死亡细胞》团队Evil Empire与Motion Twin打造。讲述年轻女战士Rose Belmont在巴黎展开的全新冒险，2.5D探索型动作游戏，系列作曲家山根美智留回归参与音乐制作，支持四人联机合作，确认支持简繁中文。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/4231820/",
      topicAngles: ["恶魔城系列40周年纪念作深度前瞻","死亡细胞团队联手Konami打造银河城新标杆","Rose Belmont女性主角与系列叙事新方向"]
    },
    {
      id: 88,
      name: "影之刃零",
      nameEn: "Phantom Blade Zero",
      date: "2026-10-29",
      developer: "灵游坊 (S-GAME)",
      publisher: "S-GAME Publishing",
      genres: ["动作RPG","武侠","魂like","3A"],
      genreClass: "action",
      platforms: ["Steam","PS5"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "国产3A武侠动作RPG巅峰之作，虚幻5引擎打造。玩家扮演心脏遭受重创的剑客，在仅余六十六天的生命中对抗神秘组织。162万份Steam愿望单登顶2026年最受期待新作，海外占比超50%。原定9月9日发售，6月3日官宣延期至10月29日。",
      priority: "high",
      heatLevel: 5,
      officialUrl: "https://store.steampowered.com/app/4115450/Phantom_Blade_Zero/",
      topicAngles: ["162万愿望单登顶：国产3A全球化现象级热度解析","影之刃零能否接棒黑神话成为下一个国产游戏里程碑","虚幻5武侠动作系统深度前瞻","海外玩家占比超50%的文化输出意义"]
    },
    {
      id: 205,
      name: "与狼同行 重制版",
      nameEn: "The Wolf Among Us Remastered",
      date: "2026-10-29",
      developer: "Telltale",
      publisher: "Telltale / PM Studios",
      genres: ["视觉小说","冒险","互动电影","推理","漫画改编"],
      genreClass: "visual-novel",
      platforms: ["Steam","PS5","Xbox","Switch","Switch 2"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "Telltale经典漫画改编互动冒险游戏《与狼同行》的高清重制版。保留全部五章 original 剧情，画面分辨率提升、动画与音频升级、帧率更流畅，新增Noir黑白模式与扩展无障碍选项。首次登陆任天堂平台。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3884860/The_Wolf_Among_Us_Remastered/",
      topicAngles: ["Telltale复活后的首部重制作品信号意义","经典互动叙事游戏在2026年的市场价值","漫画改编游戏的长线IP运营观察"]
    },
    {
      id: 206,
      name: "Gravhounds",
      nameEn: "GRAVHOUNDS",
      date: "2026-11-02",
      developer: "Octopus Panic",
      publisher: "Octopus Panic",
      genres: ["合作射击","基地建设","Roguelike","第三人称","物理驱动"],
      genreClass: "shooter",
      platforms: ["Steam","Xbox"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "支持1-4人合作的动作基地建设游戏。玩家控制生物工程改造的犬型劳工，降落在敌对星球上建造并保卫基地，在物理驱动的混乱中尽可能多地搜刮资源并撤离。首发加入Xbox Game Pass。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/2440760/GRAVHOUNDS/",
      topicAngles: ["合作建造+射击的玩法融合创新","独立游戏首发XGP策略观察","物理驱动游戏设计的趣味性边界"]
    },
    {
      id: 207,
      name: "CRYMELIGHT",
      nameEn: "CRYMELIGHT",
      date: "2026-11-04",
      developer: "FuRyu",
      publisher: "FuRyu",
      genres: ["动作","Roguelike","日系","美少女","黑暗奇幻"],
      genreClass: "action",
      platforms: ["Steam","PS5","Switch 2"],
      price: "$19.99(约¥144)",
      chinese: false,
      hot: false,
      desc: "FuRyu「Cry」系列第三作（前作为《Crystar》《Crymachina》），以死后世界为舞台的Roguelike动作游戏。背负罪孽的少女们通过忏悔获得力量，在充满情感张力的黑暗奇幻世界中战斗。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3891160/",
      topicAngles: ["FuRyu暗黑美少女动作系列的第三部进化","日系Roguelike的情感叙事差异化","小众系列的忠实粉丝生态"]
    },
    {
      id: 208,
      name: "精华 wielders",
      nameEn: "Wielders of the Essence",
      date: "2026-11-05",
      developer: "Lavapotion",
      publisher: "Lavapotion / Coffee Stain Publishing",
      genres: ["弹幕天堂","基地建设","增量","Roguelike","动作"],
      genreClass: "action",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "《征服之歌》开发商Lavapotion打造的增量基地建造弹幕生存游戏。短局运行获取资源建造建筑，解锁新能力、部队与法术，每局都能推动进度。画风精致， chaos与休闲感并存。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3546610/",
      topicAngles: ["弹幕天堂+基地建造的品类融合","《征服之歌》开发商的转型之作","增量游戏在Steam上的受众扩展"]
    },
    {
      id: 209,
      name: "暗影之路",
      nameEn: "Shadow of the Road",
      date: "2026-11-12",
      developer: "Another Angle Games",
      publisher: "Owlcat Games",
      genres: ["回合制RPG","战术","蒸汽朋克","和风","剧情驱动"],
      genreClass: "rpg",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "以1868年日本幕末时期为背景的回合制叙事RPG。在蒸汽朋克与魔法交织的奇幻日本，玩家引导流浪武士Satoru与Akira穿越内战分裂的国度，每一步战术决策都至关重要。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/1173980/Shadow_of_the_Road/",
      topicAngles: ["幕末+蒸汽朋克的独特世界观构建","《开拓者》发行商Owlcat的发行策略","波兰工作室的和风RPG创作方法论"]
    },
    {
      id: 210,
      name: "芭比 rewind",
      nameEn: "Barbie Rewind",
      date: "2026-11-12",
      developer: "Digital Eclipse",
      publisher: "Atari / Digital Eclipse",
      genres: ["复古合集","模拟","冒险","休闲","装饰"],
      genreClass: "collection",
      platforms: ["Steam","PS5","PS4","Xbox","Switch","Switch 2"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "穿越 decades 装饰芭比的梦幻屋，同时重温1991-2007年间16款经典芭比电子游戏（含从未发售的《Barbie: Vacation Adventure》）。Digital Eclipse以擅长经典游戏合集复刻著称。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4082030/Barbie_Rewind/",
      topicAngles: ["经典IP复古合集的商业价值","Digital Eclipse preservation 工作的行业意义","全年龄段游戏在硬核平台的定位"]
    },
    {
      id: 211,
      name: "树恨你",
      nameEn: "Trees Hate You",
      date: "2026-11-16",
      developer: "Tykenn",
      publisher: "Tykenn",
      genres: ["冒险","喜剧","步行模拟","恶搞","独立"],
      genreClass: "adventure",
      platforms: ["Steam"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "一款不可预测的恶搞冒险游戏，这里的树会主动试图杀死你。包含黑色幽默、多种生态区域、角色定制与可收集帽子。支持简体中文与繁体中文。",
      priority: "low",
      heatLevel: 1,
      officialUrl: "https://store.steampowered.com/app/4171850/Trees_Hate_You/",
      topicAngles: ["恶搞冒险游戏的短视频传播潜力","独立游戏中文本地化的市场回报"]
    },
    {
      id: 212,
      name: "Volvy大冒险：再 slimed",
      nameEn: "Volvy's Adventure: Reslimed",
      date: "2026-11-19",
      developer: "doinksoft",
      publisher: "Devolver Digital",
      genres: ["动作","平台跳跃","2D","像素","复古"],
      genreClass: "action",
      platforms: ["Steam"],
      price: "$4.99(约¥36)",
      chinese: false,
      hot: false,
      desc: "Devolver Digital吉祥物Volvy的像素风动作平台游戏重制版。穿越四个重新设计的世界，利用Volvy的“大手”进行悬停/滑行/挖掘，还能变身为Swolvy碾压敌人。预购享25%折扣。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4523120/",
      topicAngles: ["Devolver吉祥物IP的娱乐化营销","低价独立游戏的销量策略","复古重制的GBC风格美学"]
    },
    {
      id: 213,
      name: "哥特王朝3 经典版",
      nameEn: "Gothic 3 Classic",
      date: "2026-11-24",
      developer: "Piranha Bytes",
      publisher: "THQ Nordic",
      genres: ["动作RPG","开放世界","经典复刻"],
      genreClass: "rpg",
      platforms: ["PS5","Xbox","Switch 2"],
      price: "€29.99(约¥235)",
      chinese: false,
      hot: false,
      desc: "2006年经典开放世界动作RPG首次登陆现代主机。针对手柄重新设计UI与控制，整合Community Patch 1.75。设定在战火纷飞的大陆Myrtana，玩家扮演无名英雄成为传奇。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://gothic3classic.thqnordic.com/",
      coverUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/39500/header.jpg",
      topicAngles: ["经典RPG主机复刻的市场需求","《哥特王朝》系列的复兴之路","老游戏社区补丁的官方整合意义"]
    },
    {
      id: 214,
      name: "勇者斗恶龙 怪兽篇：枯萎的世界",
      nameEn: "DRAGON QUEST MONSTERS: The Withered World",
      date: "2026-12-03",
      developer: "Square Enix / TOSE",
      publisher: "Square Enix",
      genres: ["RPG","怪物收集","养成","回合制"],
      genreClass: "rpg",
      platforms: ["Steam","PS5","Xbox","Switch","Switch 2"],
      price: "$49.99(约¥360)",
      chinese: false,
      hot: true,
      desc: "《勇者斗恶龙》系列怪物收集RPG最新作。结识、培育并合成超过500种来自DQ系列的怪物。跟随怪物驯养师Bianca与Nera展开冒险，治愈她们患病的父亲。豪华版可提前2天游玩。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/3681610/",
      topicAngles: ["DQ怪兽篇系列暌违多年的正统续作","怪物收集品类的市场复苏趋势","Square Enix多平台同步发行策略"]
    },
    {
      id: 215,
      name: "Stage Tour",
      nameEn: "STAGE TOUR",
      date: "2026-12-10",
      developer: "RedOctane Games",
      publisher: "RedOctane Games",
      genres: ["节奏","音乐","动作","乐队","多人"],
      genreClass: "action",
      platforms: ["Steam","PS5","Xbox","Switch 2"],
      price: "待确认",
      chinese: false,
      hot: true,
      desc: "由原《吉他英雄》团队RedOctane打造的乐队节奏游戏。收录Metallica、Radiohead、Paramore、Olivia Rodrigo等90+首官方授权歌曲，横跨六十年，180+把真实Gibson/Epiphone/Kramer吉他。支持跨平台联机。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/4452700/STAGE_TOUR/",
      topicAngles: ["《吉他英雄》原班人马的节奏游戏回归","90+授权曲目的音游阵容分析","乐队外设与游戏捆绑销售商业模式"]
    },
    {
      id: 216,
      name: "流放之路2",
      nameEn: "Path of Exile 2",
      date: "2026-12-11",
      developer: "Grinding Gear Games",
      publisher: "Grinding Gear Games",
      genres: ["动作RPG","免费","在线合作","地牢探索","刷宝"],
      genreClass: "rpg",
      platforms: ["Steam","PS5","Xbox"],
      price: "免费",
      chinese: false,
      hot: true,
      desc: "备受期待的次世代动作RPG正式结束抢先体验推出1.0完整版。全新七幕战役、支持最多6人合作、新增剑客Duelist职业。免费游玩，Wraeclast大陆上独特的文化与怪物威胁等待探索。",
      priority: "high",
      heatLevel: 5,
      officialUrl: "https://store.steampowered.com/app/2694490/PathofExile_2/",
      topicAngles: ["POE2正式版对ARPG市场的冲击","免费模式+深度Build系统的商业成功","从EA到1.0的社区信任重建"]
    },
    {
      id: 218,
      name: "机动警察 案件档案",
      nameEn: "PATLABOR the Case Files",
      date: "2026-09-17",
      developer: "Chime Corporation",
      publisher: "Good Smile Company",
      genres: ["机甲","动作","冒险","动画改编"],
      genreClass: "action",
      platforms: ["Steam","PS5"],
      price: "$34.99(约¥250)",
      chinese: true,
      hot: false,
      desc: "在这款家用主机3D动作游戏中，再次体验《机动警察》中的众多经典场景。从不同视角展开游戏——在主线任务中作为特车二课执行任务，在Another Side任务中则从对手视角进行游戏。超过20台Labor登场，搭载模拟器模式。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3275400/",
      topicAngles: ["经典机甲动画IP的游戏化改编","双视角叙事在动作游戏中的应用","Good Smile Company游戏发行布局"]
    },
    {
      id: 219,
      name: "秋叶原迷踪",
      nameEn: "AKIBA LOST",
      date: "2026-09-16",
      developer: "IzanagiGames",
      publisher: "IzanagiGames",
      genres: ["动态影像","剧情","悬疑","选择"],
      genreClass: "visual-novel",
      platforms: ["Steam","PS5","Switch","Switch 2"],
      price: "待确认",
      chinese: true,
      hot: false,
      desc: "以秋叶原为舞台的长篇实写悬疑游戏。由北山宏光主演，讲述在秋叶原拍摄实写游戏过程中，现实与虚构逐渐交织的七日之谜。Steam试玩版已上线，存档可继承至正式版。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4131220/",
      topicAngles: ["实写影像游戏在日本市场的创新探索","秋叶原文化×悬疑叙事的跨界融合","IzanagiGames实写游戏系列布局"]
    },
    {
      id: 220,
      name: "狂热运输3",
      nameEn: "Transport Fever 3",
      date: "2026-09-29",
      developer: "Urban Games",
      publisher: "Paradox Interactive",
      genres: ["模拟经营","策略","交通","建造","开放世界"],
      genreClass: "simulation",
      platforms: ["Steam","PS5","Xbox"],
      price: "¥198(标准版)",
      chinese: true,
      hot: true,
      desc: "更宏大、更深入、更动感的运输大亨养成游戏强势回归。利用超过一个世纪以来不断发展的交通方式，打造改变世界格局的陆海空交通路线。Steam国区¥198起，豪华版¥258，支持简繁中文。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/3493540/Transport_Fever_3/",
      topicAngles: ["狂热运输系列第三代：运输模拟游戏的进化","Paradox Interactive模拟经营游戏布局","交通模拟游戏的国区定价策略"]
    },
    {
      id: 221,
      name: "制服女友3",
      nameEn: "Seifuku Kanojo 3",
      date: "2026-09-10",
      developer: "ENTERGRAM",
      publisher: "ENTERGRAM",
      genres: ["视觉小说","恋爱","模拟","日常"],
      genreClass: "visual-novel",
      platforms: ["PC","Switch"],
      price: "¥7,573(约¥370)",
      chinese: false,
      hot: false,
      desc: "全国掀起「私服通学热潮」，学生改穿便服上学成为流行趋势，使得推广制服魅力的「制服女友活动」面临存亡危机。从美国返国的新角色伊规须爱叶将加入主角群，协助展开新的制服推广计划。日文版，PC/Switch平台。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://www.entergram.co.jp/seikano3/",
      coverUrl: "https://www.entergram.co.jp/seikano3/img/top_main.jpg",
      topicAngles: ["恋爱模拟游戏在日本市场的持续生命力","制服文化×恋爱游戏的差异化定位"]
    },
    {
      id: 222,
      name: "吞吞堡垒",
      nameEn: "Wanderburg",
      date: "2026-09-08",
      developer: "Randwerk",
      publisher: "Sidekick Publishing",
      genres: ["动作","Roguelike","策略","中世纪"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "极简风格的中世纪Roguelike，驾驶移动城堡冲入战场！吞噬整座村庄，打造模块化武装系统，并在每一次碾碎敌方要塞后不断壮大自己。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3624140/Wanderburg/",
      topicAngles: ["移动城堡Roguelike的创新玩法","极简风格中世纪策略游戏的市场潜力"]
    },
    {
      id: 223,
      name: "守墓人2",
      nameEn: "Graveyard Keeper 2",
      date: "2026-09-22",
      developer: "Lazy Bear Games",
      publisher: "tinyBuild",
      genres: ["模拟经营","RPG","冒险","黑色幽默"],
      genreClass: "simulation",
      platforms: ["Steam","PS5","Xbox","Switch","Switch 2"],
      price: "$24.99(约¥178)",
      chinese: true,
      hot: true,
      desc: "史上最不靠谱的中世纪墓园模拟器续作。重建城镇、打理墓园、实现生产自动化，率领你的亡灵大军奔赴战场，把僵尸生意做大做强。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/4358690/Graveyard_Keeper_2/",
      topicAngles: ["守墓人2：黑色幽默模拟经营的回归","tinyBuild发行的独立游戏成功密码","亡灵大军+自动化经营的荒诞组合"]
    },
    {
      id: 225,
      name: "Tiny Eden",
      nameEn: "Tiny Eden",
      date: "2026-09-07",
      developer: "Bajka Games",
      publisher: "Digital Vortex Entertainment",
      genres: ["休闲","模拟","治愈","农场"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "在未来城市中心的温馨第一人称农场模拟游戏。种植植物、烹饪收获，发现新品种，将你的公寓从阳台小园发展到屋顶天堂。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3375110/Tiny_Eden/",
      topicAngles: ["城市农场模拟的治愈体验","第一人称种植游戏的沉浸感"]
    },
    {
      id: 226,
      name: "Frutiger Home",
      nameEn: "Frutiger Home",
      date: "2026-09-28",
      developer: "frutigerdev",
      publisher: "frutigerdev",
      genres: ["模拟","装饰","建造","合作","休闲"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "Frutiger Aero风格的温馨合作房屋装饰游戏。选择房屋布局，添加各种Frutiger主题装饰，与朋友一起打造梦想之家。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3935530/Frutiger_Home/",
      topicAngles: ["Frutiger Aero美学在游戏中的应用","合作装饰游戏的社交体验"]
    },
    {
      id: 227,
      name: "Stream Train",
      nameEn: "Stream Train",
      date: "2026-10-15",
      developer: "Half Past Yellow",
      publisher: "Half Past Yellow",
      genres: ["合作","恐怖","生存","直播"],
      genreClass: "horror",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "最多6人合作恐怖冒险游戏。玩家组队控制老式蒸汽火车，穿越充满神秘生物的荒野，通过直播旅程、调查废弃建筑和记录奇异生物来吸引观众。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/4071650/Stream_Train/",
      topicAngles: ["直播生存恐怖的合作玩法创新","6人合作恐怖游戏的市场空白"]
    },
    {
      id: 228,
      name: "深渊尽头",
      nameEn: "End of Abyss",
      date: "2026-10-01",
      developer: "Section 9 Interactive",
      publisher: "Epic Games Publishing",
      genres: ["恐怖","动作","Metroidvania","射击"],
      genreClass: "horror",
      platforms: ["Epic","PS5","Xbox"],
      price: "待确认",
      chinese: false,
      hot: true,
      desc: "前《小小梦魇》团队新作，黑暗科幻恐怖Metroidvania射击游戏。在深渊中探索，揭开被扭曲世界的秘密。Epic Games Store独占发行。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.epicgames.com/",
      coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9xhm.jpg",
      topicAngles: ["前小小梦魇团队的恐怖新作","Epic独占发行的市场策略","科幻恐怖Metroidvania的玩法融合"]
    },
    {
      id: 229,
      name: "Roguecraft DX",
      nameEn: "Roguecraft DX",
      date: "2026-09-10",
      developer: "Badger Punch Games",
      publisher: "Thalamus Digital",
      genres: ["Roguelike","地牢探险","回合制","RPG"],
      genreClass: "rpg",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "Roguelike地牢探险游戏，回合制战斗，程序生成的地下城，丰富的角色Build和道具组合。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3674680/Roguecraft_DX/",
      topicAngles: ["Roguelike地牢探险的玩法深度","回合制战斗系统的策略性"]
    },
    {
      id: 230,
      name: "Monster Alchemy",
      nameEn: "Monster Alchemy",
      date: "2026-09-10",
      developer: "Team Metacarpo",
      publisher: "Team Metacarpo",
      genres: ["生物收集","探索","回合制RPG","冒险"],
      genreClass: "adventure",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "生物收集探索冒险游戏。捕捉、融合和培育各种怪物，组建队伍探索广阔世界，发现隐藏的秘密。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4013510/Monster_Alchemy/",
      topicAngles: ["生物收集类游戏的市场观察","怪物融合培育系统的创新"]
    },
    {
      id: 231,
      name: "Ex Sanguis",
      nameEn: "Ex Sanguis",
      date: "2026-09-10",
      developer: "Lightbulb Crew",
      publisher: "Firesquid",
      genres: ["策略","回合制","Roguelike","抢先体验"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "策略回合制Roguelike游戏，在抢先体验中推出。构建你的队伍，探索危险区域，在战术战斗中生存下来。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3275050/Ex_Sanguis/",
      topicAngles: ["回合制策略Roguelike的玩法组合","抢先体验模式的策略游戏迭代"]
    },
    {
      id: 232,
      name: "BeaterCore",
      nameEn: "BeaterCore",
      date: "2026-09-09",
      developer: "Artem Arbatsky",
      publisher: "Artem Arbatsky",
      genres: ["竞速","驾驶","街机","独立"],
      genreClass: "action",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "街机风格竞速驾驶游戏。简单易上手的操控，丰富的赛道和车辆选择，快节奏的赛车体验。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3711050/BeaterCore/",
      topicAngles: ["街机竞速游戏的复古魅力","独立赛车游戏的玩法创新"]
    },
    {
      id: 233,
      name: "Thousand Hells",
      nameEn: "Thousand Hells: The Underworld Heists",
      date: "2026-09-08",
      developer: "A Sharp",
      publisher: "Kitfox Games",
      genres: ["RPG","策略","神话","冒险"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "以神话为背景的RPG策略游戏。在地狱世界中策划和执行劫案，招募神话生物组建团队，挑战各种危险任务。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3794210/Thousand_Hells_The_Underworld_Heists/",
      topicAngles: ["神话背景RPG策略游戏的市场定位","Kitfox Games发行独立游戏策略"]
    },
    {
      id: 234,
      name: "Magical Blush",
      nameEn: "Magical Blush",
      date: "2026-09-10",
      developer: "Alkacer Game Studio",
      publisher: "DANGEN Entertainment",
      genres: ["动作","冒险","Metroidvania","魔法"],
      genreClass: "action",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "俯视角魔法Metroidvania游戏。探索互相连通的世界，学习各种魔法技能，击败强大的敌人，揭开世界的秘密。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3488640/Magical_Blush/",
      topicAngles: ["俯视角Metroidvania的玩法设计","魔法系统的战斗深度"]
    },
    {
      id: 235,
      name: "愚蠢的方式建造",
      nameEn: "Dumb Ways to Build",
      date: "2026-09-10",
      developer: "Dumb Ways to Die",
      publisher: "Dumb Ways to Die",
      genres: ["动作","多人合作","物理","休闲"],
      genreClass: "action",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "混乱的物理合作建造游戏。与朋友组队，在危险的建筑工地上合作建造，使用各种工具和装备完成任务。物理引擎驱动的搞笑玩法，支持在线合作。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/4412320/Dumb_Ways_to_Build/",
      topicAngles: ["物理合作建造游戏的社交乐趣","Dumb Ways to Die IP衍生游戏"]

    },
    {
      id: 236,
      name: "蘑菇与阴郁",
      nameEn: "Shroom and Gloom",
      date: "2026-09-11",
      developer: "Team Lazerbeam",
      publisher: "Devolver Digital",
      genres: ["牌组构建","卡牌","Roguelike","回合制"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "第一人称真菌朋克风格双牌组构建Roguelike游戏。面对大群怪物蘑菇，构建双牌组连击，在回合制战斗中释放强力组合技。Devolver Digital发行的独立精品。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3271280/Shroom_and_Gloom/",
      topicAngles: ["真菌朋克美术风格的市场差异化","双牌组构建Roguelike的玩法创新"]

    },
    {
      id: 237,
      name: "动漫商店模拟器",
      nameEn: "Anime Shop Simulator",
      date: "2026-09-12",
      developer: "One More Time",
      publisher: "One More Time / Polnoch",
      genres: ["模拟经营","动漫","在线合作","休闲"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "经营自己的动漫商店。单人游玩或与朋友组队4人合作，管理货架上的漫画、手办和收藏卡牌，在沉浸式第一人称视角中发展你的二次元商业帝国。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3393280/Anime_Shop_Simulator/",
      topicAngles: ["动漫主题模拟经营游戏的市场空间","4人在线合作模拟经营体验"]

    },
    {
      id: 238,
      name: "农场营地",
      nameEn: "Farming Camp",
      date: "2026-09-24",
      developer: "Innerfire Studios",
      publisher: "SOEDESCO",
      genres: ["模拟经营","农场","休闲","冒险"],
      genreClass: "simulation",
      platforms: ["Steam","PS5","Xbox","Switch"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "温馨的单人农场管理游戏。扮演雄心勃勃的少女，在营地中与同伴竞争成为最佳农民。管理农场、完成日常任务、参与迷你游戏，体验农场生活的乐趣。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2985880/Farming_Camp/",
      topicAngles: ["温馨农场模拟游戏的市场成熟度","与星露谷物语的差异化竞争"]

    },
    {
      id: 239,
      name: "密室协议",
      nameEn: "Backrooms Protocol",
      date: "2026-09-11",
      developer: "Niche",
      publisher: "Niche",
      genres: ["恐怖","探索","在线合作","生存"],
      genreClass: "horror",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "扮演M.E.G.研究员被送入Backrooms完成任务。遵照指示，不要提问。独自或与最多4名玩家组队探索令人不安的写实Backrooms关卡。完成目标，不惜一切代价活着出来。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/4287480/Backrooms_Protocol/",
      topicAngles: ["Backrooms都市传说改编游戏热度观察","在线合作恐怖探索游戏市场"]

    },
    {
      id: 240,
      name: "暗夜曲",
      nameEn: "Nocturne",
      date: "2026-09-23",
      developer: "Pracy Studios",
      publisher: "Pracy Studios",
      genres: ["RPG","冒险","独立","节奏"],
      genreClass: "rpg",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "数字来世的RPG冒险。人类已消亡，唯有数字来世沉默千年。直到现在。Nocturne丰富的叙事将让你质疑活着的意义，在崩坏却美丽的世界中穿行，体验独特的节奏战斗系统。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/1374860/Nocturne/",
      topicAngles: ["节奏战斗RPG的创新玩法","数字来世主题的叙事探索"]

    },
    {
      id: 241,
      name: "创世编年史",
      nameEn: "Creator Chronicles",
      date: "2026-09-14",
      developer: "Origin Studio",
      publisher: "Gamersky Games / Origin Studio",
      genres: ["城镇建造","像素","经营","角色扮演"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "像素风城镇建造经营游戏。扮演公会大师，从零规划并建设城镇，招募并培养冒险者小队，探索世界、完成任务，逐步扩张你的城镇版图。",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3947460/Creator_Chronicles/",
      topicAngles: ["像素城镇建造游戏的玩法观察","公会经营与冒险者招募的养成循环"]
    },
    {
      id: 242,
      name: "破碎传说：别说谎",
      nameEn: "BrokenLore: DON'T LIE",
      date: "2026-09-09",
      developer: "Serafini Productions",
      publisher: "Wired Productions / Serafini Productions",
      genres: ["恐怖","冒险","心理恐怖","叙事"],
      genreClass: "horror",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "日式心理恐怖游戏，探索创伤、孤立和破碎的现实，感知逐渐变得不可靠。在扭曲的叙事中探索真相，谎言与现实的界限逐渐模糊。",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3886200/BrokenLore_DONT_LIE/",
      topicAngles: ["心理恐怖游戏的叙事手法","第一人称恐怖冒险的市场定位"]

    },
    {
      id: 243,
      name: "日落峰会",
      nameEn: "Sunset Summit",
      date: "2026-09-09",
      developer: "Joe Fender / Andrew Fender",
      publisher: "Future Friends Games",
      genres: ["冒险","独立","开放世界"],
      genreClass: "adventure",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "1-8人合作攀爬游戏！出发进行轻松但具有挑战性的攀登，设有定期检查点。使用冰镐、绳索、弹簧单高跷、物品运输无人机等工具到达山顶。记得注意脚下！",
      priority: "low",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3874450/",
      topicAngles: ["开放世界冒险游戏的独立制作趋势","攀爬探索玩法设计"]

    },
    {
      id: 244,
      name: "淡路岛军阀",
      nameEn: "Warlord: Awaji",
      date: "2026-09-09",
      developer: "Darkmatter Games",
      publisher: "Darkmatter Games",
      genres: ["策略","历史","日本战国","战争"],
      genreClass: "strategy",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "率领武士入侵神秘的淡路岛！招募、晋升和升级你的武士，在日本封建时代的古老世界中穿行。使用武士武器和策略征服整个岛屿，成为真正的军阀！",
      priority: "medium",
      heatLevel: 2,
      officialUrl: "https://store.steampowered.com/app/3123060/Warlord_Awaji/",
      topicAngles: ["日本战国题材策略游戏的市场","历史策略游戏的玩法深度"]

    },
    {
      id: 245,
      name: "Kalanoro",
      nameEn: "Kalanoro",
      date: "2026-09-24",
      developer: "Red Raketa Studio",
      publisher: "New Tales / SEGA",
      genres: ["动作冒险","平台跳跃","音乐","探索"],
      genreClass: "adventure",
      platforms: ["Steam","PS5","Switch"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "以马达加斯加民间传说为灵感的动作冒险平台游戏。组建一支狐猴艺术家乐队，探索色彩缤纷的雷姆利亚世界，用音乐的力量对抗邪恶女巫，最终解放这座被压迫的岛屿。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3158820/Kalanoro/",
      topicAngles: ["马达加斯加民间传说的文化表达","音乐与动作冒险的玩法融合"]
    },
    {
      id: 252,
      name: "巫师3：狂猎 重制版",
      nameEn: "The Witcher 3: Wild Hunt - Remastered",
      date: "2026-09-29",
      developer: "CD PROJEKT RED",
      publisher: "CD PROJEKT RED",
      genres: ["角色扮演","开放世界","动作","奇幻"],
      genreClass: "rpg",
      platforms: ["Steam","PS5","Xbox","Switch 2"],
      price: "免费升级(原版拥有者)",
      chinese: true,
      hot: true,
      desc: "CD PROJEKT RED 于 Gamescom 2026 公布的《巫师3：狂猎》重制版，9月29日登陆 PC、PS5、Xbox Series X|S 并首次推出 Switch 2 原生版本。带来画面、性能与玩法全面升级，原版拥有者可免费升级。",
      priority: "high",
      heatLevel: 5,
      officialUrl: "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
      topicAngles: ["年度RPG重制版免费升级策略","CDPR口碑回暖与系列IP运营","Switch 2 移植的玩家期待度"]
    },
    {
      id: 253,
      name: "永恒之塔2",
      nameEn: "AION 2",
      date: "2026-10-05",
      developer: "NC",
      publisher: "NC",
      genres: ["MMORPG","开放世界","飞行战斗","多人"],
      genreClass: "rpg",
      platforms: ["Steam","PC"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "NCsoft《永恒之塔》正统续作，虚幻引擎5打造，以天空为战场。玩家可选择阵营、觉醒为天族，在比原作大36倍的世界中展开阵营战争。支持简体中文，全球10月5日正式发售（9月30日可抢先体验）。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/3393110/AION_2/",
      topicAngles: ["经典MMO续作的市场前景","虚幻5引擎开放世界MMO的技术展示","国内MMO玩家回流现象观察"]
    },
    {
      id: 254,
      name: "美少女梦工厂：预言之子",
      nameEn: "Princess Maker: Children of Revelation",
      date: "2026-09-30",
      developer: "GEAR2",
      publisher: "GEAR2",
      genres: ["模拟养成","生活模拟","奇幻","单机"],
      genreClass: "simulation",
      platforms: ["Steam"],
      price: "$34.99",
      chinese: true,
      hot: false,
      desc: "时隔约18年回归的美少女梦工厂系列新作，9月30日脱离抢先体验正式发售。扮演监护人将年幼少女养育成人，培养其资质与梦想，谱写专属养成故事。支持简繁体中文。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3438810/Princess_Maker__Children_of_Revelation/",
      topicAngles: ["经典养成IP回归的市场表现","模拟养成游戏的情感共鸣设计"]
    },
    {
      id: 255,
      name: "最终幻想：共鸣",
      nameEn: "FINAL FANTASY RESONANCE",
      date: "2026-10-22",
      developer: "Square Enix / LANCARSE",
      publisher: "Square Enix",
      genres: ["RPG","HD-2D","回合制","奇幻","像素"],
      genreClass: "rpg",
      platforms: ["Steam","PS5","Xbox","Switch","Switch 2"],
      price: "¥268(标准版)",
      chinese: true,
      hot: true,
      desc: "《最终幻想》系列首款HD-2D作品，围绕水晶展开的物语。融合回合制指令战斗与能力变更等系列经典要素，收录丰富的重复游玩内容。由Square Enix与LANCARSE联合开发，支持简繁中文。",
      priority: "high",
      heatLevel: 5,
      officialUrl: "https://store.steampowered.com/app/3259780/FINAL_FANTASY_RESONANCE/",
      topicAngles: ["最终幻想系列首款HD-2D作品深度前瞻","FF经典要素与HD-2D美学的融合","回合制JRPG在2026年的市场表现"],
      isNewToday: true
    },
    {
      id: 256,
      name: "沉星之序",
      nameEn: "Order of the Sinking Star",
      date: "2026-10-08",
      developer: "Thekla",
      publisher: "Arc Games / Gamirror Games",
      genres: ["解谜","冒险","叙事","独立"],
      genreClass: "puzzle",
      platforms: ["Steam","PS5","Switch 2"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "《见证者》《时空幻境》传奇制作人Jonathan Blow历时十年打造的解谜冒险新作。在充满魔法与谜团的世界中解开超过1000个相互关联的手工谜题，发现独特的可玩角色，掌握不断进化的玩法机制。Steam试玩版已上线。",
      priority: "high",
      heatLevel: 4,
      officialUrl: "https://store.steampowered.com/app/499170/Order_of_the_Sinking_Star/",
      topicAngles: ["Jonathan Blow十年新作深度前瞻","见证者之后解谜游戏的进化方向","1000+手工谜题的内容量评估"],
      isNewToday: true
    },
    {
      id: 257,
      name: "歧路旅人 & 歧路旅人II",
      nameEn: "OCTOPATH TRAVELER & OCTOPATH TRAVELER II",
      date: "2026-10-01",
      developer: "Square Enix / ACQUIRE",
      publisher: "Square Enix",
      genres: ["RPG","HD-2D","回合制","像素","移植"],
      genreClass: "rpg",
      platforms: ["Switch 2"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "《歧路旅人》系列8周年纪念，初代与《歧路旅人II》于10月1日登陆Nintendo Switch 2。分辨率与帧率较Switch版全面提升，另有《歧路旅人1+2》实体合辑同步发售。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/1971650/OCTOPATH_TRAVELER_II/",
      topicAngles: ["歧路旅人系列8周年Switch 2移植","HD-2D美学在次世代主机的表现","Square Enix经典IP多平台策略"],
      isNewToday: true
    },
    {
      id: 258,
      name: "战锤40K：爆弹枪2",
      nameEn: "Warhammer 40,000: Boltgun 2",
      date: "2026-10-14",
      developer: "Auroch Digital",
      publisher: "Big Fan Games / Devolver Digital",
      genres: ["复古FPS","射击","战锤40K","动作","血腥"],
      genreClass: "shooter",
      platforms: ["Steam","PS5","Xbox"],
      price: "待确认",
      chinese: true,
      hot: true,
      desc: "好评复古FPS《Warhammer 40,000: Boltgun》的续作。扮演极限战士马鲁姆·凯多或战斗修女奈拉·维拉思，迎战更多敌人、使用更多武器，以更多方式净化异端。Steam试玩版已上线，Switch 2版稍后发售。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/3115160/Warhammer_40000_Boltgun_2/",
      topicAngles: ["复古FPS续作爆弹枪2的暴力美学","战锤40K授权游戏的产品线观察","Devolver Digital发行复古射击游戏策略"],
      isNewToday: true
    },
    {
      id: 259,
      name: "霜港迷城",
      nameEn: "Frosthaven",
      date: "2026-10-15",
      developer: "Snapshot Games",
      publisher: "Arc Games",
      genres: ["战术RPG","回合制","桌游改编","黑暗奇幻","合作"],
      genreClass: "strategy",
      platforms: ["Steam","Epic"],
      price: "$39.99(约¥288)",
      chinese: false,
      hot: true,
      desc: "备受好评的桌游《幽港迷城》续作《霜港迷城》数字版1.0正式上线。由Isaac Childres与Cephalofair Games打造，暗黑奇幻战术RPG融合经典桌游体验，历经一年抢先体验后推出完整版，收录全部早期内容。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2347080/Frosthaven/",
      topicAngles: ["现象级桌游的数字版进化","幽港迷城到霜港迷城的IP延续","战术RPG与桌游融合的市场前景"],
      isNewToday: true
    },
    {
      id: 260,
      name: "Kingmakers",
      nameEn: "Kingmakers",
      date: "2026-10-08",
      developer: "Redemption Road Games",
      publisher: "tinyBuild",
      genres: ["动作","模拟","策略","沙盒","中世纪","抢先体验"],
      genreClass: "action",
      platforms: ["Steam"],
      price: "待确认",
      chinese: false,
      hot: true,
      desc: "另类架空历史沙盒游戏，回到500年前的中世纪英格兰，用现代军事火力改写历史。驾驶坦克、携带M16在15世纪战场与骑士弩手混战。Redemption Road开发、tinyBuild发行，Steam愿望单极高，以抢先体验形式发售。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2109770/Kingmakers/",
      topicAngles: ["现代武器碾压中世纪的沙盒创意爆款","Kingmakers病毒式传播的营销启示","抢先体验策略在中型独立游戏的应用"],
      isNewToday: true
    },
    {
      id: 261,
      name: "Tenebris Somnia",
      nameEn: "Tenebris Somnia",
      date: "2026-10-16",
      developer: "Andrés Borghi / Saibot Studios",
      publisher: "New Blood Interactive",
      genres: ["生存恐怖","复古","2D","解谜","真人影像"],
      genreClass: "horror",
      platforms: ["Steam","PS5","PS4","Xbox","Switch","Switch 2"],
      price: "待确认",
      chinese: false,
      hot: false,
      desc: "复古生存恐怖游戏，致敬经典《生化危机》《寂静岭》但以2D像素呈现。独特之处在于过场动画采用真人实拍恐怖影像，在噩梦中解谜、对抗可怕生物，揭开令人不安的故事真相。",
      priority: "medium",
      heatLevel: 3,
      officialUrl: "https://store.steampowered.com/app/2121510/Tenebris_Somnia/",
      topicAngles: ["真人影像融入复古恐怖游戏的创新","New Blood Interactive独立恐怖产品线","2D生存恐怖的情怀与进化"],
      isNewToday: true
    }
  ];